#配置端口
server:
  port: 8585
spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spacecloud?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    initialSize: 5
    maxActive: 100
    minIdle: 3
    maxWait: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #禁用thymeleaf缓存
#  thymeleaf:
#    cache: false
#    enabled: true
#    enable-spring-el-compiler: true


#pagehelper配置
pagehelper:
  helper-dialect: mysql

#配置Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.nuaa.entity
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
  global-config:
    db-config:
      #主键类型
      id-type: auto
      #全局表前缀
      table-prefix: t_
      #驼峰下划线转换
      table-underline: true
      #逻辑删除配置
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    ##配置返回数据库（column下划线命名&&返回java实体是驼峰命名），自动匹配无需as（没开启这个，sql需要写as:select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
#日志输出
logging:
  level:
    cn.nuaa.dao: debug

#管理员邀请码
admin:
  invitationCode: asdfg